### ISSUE TITLE
[Bug? / Weird Interaction] AngelChest & ProNouns

### ISSUE THREAD

**Issue by SleepyCatten** [JEFF-Media-GbR/issue-tracker#2]
Hi,

This server is running Paper version git-Paper-150 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT).

If AngelChest is run alongside another plugin called ProNouns and Simple Voice Mod, AngelChest seems to produce a warning message on startup:
https://gist.github.com/SleepyCatten/eba97710fbca625c64b716f426f5d3dd

The issue seems to be with ProNouns, as the error does not occur if this plugin is disabled. You can find ProNouns here:
https://github.com/lucypoulton/ProNouns

Please let me know if you require further details.

Kind regards

**Comment by lucyydotp** [comment]
Sorry this is a problem on my end, fixing tomorrow.

**Comment by noramibu** [comment]
Looks like @lucypoulton already fixed
